"""add useful indexes

Revision ID: 7866e78069eb
Revises: cc1cd0ec55e6
Create Date: 2025-09-11 19:51:48.867150

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '7866e78069eb'
down_revision = 'cc1cd0ec55e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_expenses_user_date', 'expenses', ['user_id', 'date'], unique=False)
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_subscriptions_user_created', 'subscriptions', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_subscriptions_user_nextpay', 'subscriptions', ['user_id', 'next_payment_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subscriptions_user_nextpay', table_name='subscriptions')
    op.drop_index('ix_subscriptions_user_created', table_name='subscriptions')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_index('ix_expenses_user_date', table_name='expenses')
    # ### end Alembic commands ###
