"""add refresh tokens

Revision ID: 797b01e4d9d1
Revises: 7866e78069eb
Create Date: 2025-09-11 19:57:38.430366

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '797b01e4d9d1'
down_revision = '7866e78069eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
